### ISSUE TITLE
Missing spawns, bad icons

### ISSUE THREAD

**Issue by ItsCEED** [CptWesley/NewWorldMinimap#149]
Running around the world i can see a lot of spawns are missing from the map, even some outdated ones are there. You should look into this and keep it up to date.

Icon wise, im willing to recreate every needed icon (with original image of what we farming), if this is an option please let me know how can i proceed

**Comment by CptWesley** [comment]
Our icons are retrieved from https://www.newworld-map.com, so we re not in control of adding or removing icons. I'm also not sure what you mean by "even some outdated ones". Do you mean you went to some icon and the resource wasn't there? Could it be possible that it was mined/harvested/cut down by someone else before you got there?

Feel free to contribute any missing icons.

**Comment by ItsCEED** [comment]
Ummm, im I doing something wrong? :|

![image](https://user-images.githubusercontent.com/20998381/139638181-83e23d33-61e9-41ae-9fe3-7354fae0547c.png)

That's what I'm saying about icons...

Also, I'm talking about spawns which are ingame but not on the map

**Comment by CptWesley** [comment]
I'm not sure what I should be seeing on the picture.

And again for the missing markers, please report them at https://www.newworld-map.com/

**Comment by ItsCEED** [comment]
https://www.newworld-map.com/ has different images, and different spawns somehow, that's why im confused

**Comment by CptWesley** [comment]
![image](https://user-images.githubusercontent.com/9980136/139642931-9974cdf8-0125-4326-bd8f-e00127c38cda.png)

They use different icons, but that's it. I don't see any icons that are present on their map compared to ours.
