### ISSUE TITLE
[Feature Request] Possible mumble link integration?

### ISSUE THREAD

**Issue by Kuratius** [CptWesley/NewWorldMinimap#152]
It might be interesting to provide the coordinates via the mumble link interface to allow for positional audio.

https://wiki.mumble.info/wiki/Link

https://wiki.mumble.info/wiki/Games

This may also allow for easier sharing of friend's coordinates and showing them on the minimap, assuming they are connected to the same mumble server.

**Comment by CptWesley** [comment]
New World doesn't support Mumble Link

**Comment by Kuratius** [comment]
The idea here was more to provide the mumble link interface through overwolf.

**Comment by Kuratius** [comment]
@CptWesley
