### ISSUE TITLE
Don't work idk why

### ISSUE THREAD

**Issue by GooseRuby** [CptWesley/NewWorldMinimap#16]
its don't work :(
![image](https://user-images.githubusercontent.com/62210241/136440783-1408795d-c62f-405b-86df-cfcd4a354049.png)

settings:
win11, 1920x1080, fullscreen
![image](https://user-images.githubusercontent.com/62210241/136440891-c8312fff-f29b-4a20-8525-6d89e3ca64b4.png)

**Comment by CptWesley** [comment]
Are you running the game on a different monitor than your primary monitor?

**Comment by Ruddy2007** [comment]
@CptWesley Do you have discord or some form of IM? I was building my own version of this when I found... well this, so I was going to use it as my base code. But if you would like help with this it might be good to have a chat and both work on this version if you are up for it? 

At the moment looking at this code there are some issues and I cannot compile it.

**Comment by CptWesley** [comment]
No further information provided. Closing.
