### ISSUE TITLE
Opt In option?

### ISSUE THREAD

**Issue by Tomatix** [CptWesley/NewWorldMinimap#161]
Other minimap applications still work, given the developers stance that no one has been banned from using any mini-map AND they would give users a clear warning if they ever change their stance on it, i.e. grace period.

I think Instead of disabling the map for everyone no question, I think there should be an option where you must opt in and fully understand you might be putting your account in jeopardy if you want to use this map.

Reason: 

There is no way to disable auto updates in overwolf- which checks for updates every 8 hours or so. However users can download older versions , i.e. 1.2 and use it until the auto update. re-install/install so having an opt in would just make it more convenient since determined users will use the map anyways.

**Comment by CptWesley** [comment]
They have given the minimap developers a warning that they have changed their policy. We are currently in the grace period. Tomorrow the grace period ends. We were instructed to remove the features before Tuesday.

I have already said this many times and I don't know how I can stress it more, but this is not our decision. We were instructred by AGS (through Overwolf) to remove these things.
