### ISSUE TITLE
Location streaming seemed to have stopped worked today.

### ISSUE THREAD

**Issue by ljrobison** [CptWesley/NewWorldMinimap#165]
Hello,

Today I noticed the location streaming for use with 3rd party websites (or the external included map) seems to have broke. It will no longer keep track of the players location past the initial login location. 

![chrome_TzzremwLcx](https://user-images.githubusercontent.com/2848664/206566018-0cc1abb2-3a4b-475b-8f55-da9132f3c2d9.png)

As you can see from the above screenshot, it seems to be working. However my location will not update from that point as I move around. However, refreshing seems to display my current location again, but still will not track if that helps. 

I haven't changed any settings, and have completely uninstalled both Overwolf, NWMM, and New World and proceeded with clean installs but the issue still persists. It could still be on my end. But I figured I should post here regardless in case it does tend to be an issue or if anyone knows how I can fix my problem.

Thank you.

Edit: It seems the internal map works fine. But any streaming to external browser via the included one or using NewWorld-Map seems to provide the above issue.

**Comment by CptWesley** [comment]
The application you are showing is not our application.
