### ISSUE TITLE
Don't work - Ultrawide 3440x1440

### ISSUE THREAD

**Issue by Geksli** [CptWesley/NewWorldMinimap#21]
![Безымянный](https://user-images.githubusercontent.com/81643249/136562972-392b25ae-0b6e-43e0-88ce-ba750bfaca93.png)

can you fix this?
best regards from Russia :)

**Comment by Geksli** [comment]
i use one monitor - 34 Xiaomi Mi Curved

**Comment by Fengi5520** [comment]
Check scaling on your monitors. I had my 1440 monitor with 125% scaling, and the program didn't work until I changed to 100%

**Comment by Geksli** [comment]
after the last release - I confirm the work on the resolution 3440x1440
by the way, the solution with disabling dynamic resolution did not help with the previous build.
can be closed.
