### ISSUE TITLE
Suggestion: Option to configure the reading position coordinates on screen

### ISSUE THREAD

**Issue by christiangusukuma** [CptWesley/NewWorldMinimap#23]
If there was a way to draw a box over or choose the coordenates of the screenshots I think it would fix a lot of problems on different screens/resolutions.

In my case it reading on a wrong location from the game coordenates, as you can see its reading the window title which is more to the left than the coordenates.
![Captura de tela 2021-10-08 133246](https://user-images.githubusercontent.com/9649427/136592044-10e516e8-6dcf-4284-8086-befeb0b1cb15.png)

To illustrate my ideia: Is it possible to have a bounding box which you can draw when initializing the app? Something like this:

https://user-images.githubusercontent.com/9649427/136601948-6df79dec-6872-4799-8172-aed2606d66bb.mov

**Comment by Scott-Norwood** [comment]
This really would, out of all enhancements mentioned thus far, this one should be the base enhancement. Due to the fact it will open up functionality and usability.

**Comment by CptWesley** [comment]
Closing because not relevant for upcoming Overwolf version.
