### ISSUE TITLE
Failing to read OCR

### ISSUE THREAD

**Issue by keidrolis** [CptWesley/NewWorldMinimap#3]
Not working for me. Running on a 3440x1440 monitor, full screen.

Please let me know what other info I can provide to help debug.

Sample from console if it helps:
Read: PUDSALLAVIT LOVL? ,OIL, VYIVI,HVUN, LIL IVI)
202: Failure
Read: PUDSALLAVIT LOVL? ,OIL, VYJIVI,HVUN, C2ILs IVI)
203: Failure
Read: PUDSALLAVIT LOVL? ,OIL, VYJIVI,HVUN, C2ILs IVI)
204: Failure
Read: PUDSALLAVIT LOVL? ,OIL, VYIVILASVUN, C2ILs IVI)
205: Failure
Read: PUDSALLAVIT LIEV? ,OIL, VYIVI,ASVUN, C2ILs IVI)
206: Failure
Read: PUDSALLAVIT LOVL? ,OIL, VYIVI,AHVUN, C2ILs IVI)
207: Failure
Read: PUDSALLAVIT LOVL? ,OIL, VYJIVI,AHVUN, C2ILs/VUIj
208: Failure
Read: PUDSALLAVIT LOVL? ,OIL, VYGIVILSVUN, C2ILs/VUIj
209: Failure

**Comment by Typ33** [comment]
The same goes for 2560 x 1440

`Read: PVUDLELVUII LPLVvl és, 290, 2910,.870, FU,1LeZeZ |]
6090: Failure
Read: PVUDLELVUII LPLVvl és, 290, 2910,.870, FU,1LeZeZ |]
6091: Failure
Read: PUSALLIVIE PLVULCI,UUF, 2974/4 .-UUEL, MIF LJ
6092: Failure
Read: PUSALLIVIE PLVUILCI,UUY, 29/4 ,UUE, WIL IAL
6093: Failure
Read: PUSLALIVIE PLVILCZI,UUF, 2974 .UUE, MILF LJ
6094: Failure
Read: PUSALLIVIE PLVULCI,UUF, 29h 4 ,UUE, MI. FI/ LJ
6095: Failure
Read: PUSALLIAVIL PLULEI., 24h, 2ILYS - IL, MIL ILYJ
6096: Failure
Read: PUSLLEAVIL LAVALZILLUU, 2IL/A LHL I, SHI ILLS
6097: Failure
Read: PUSLLAVIT LAVA LZI,. LUN, 2ILA LHL I, SHI ILLS
6098: Failure
Read: PVUILLLVIN LAVI ZIV LE, 2AILF tp PH, MIAH!
6099: Failure
Read: PFVUSLLAVITL LPAULEZI,LYVO, 2ILf pf ODI, MIL fl IL)
6100: Failure
Read: PUSLELVIL PLULZI,. 2IL, 2LILF «pF IDYV, WIL /ONJ
6101: Failure
Read: PUSLLEAVIL LPAVALZILUUL, 2ILF FRE, MIL IHD]
6102: Failure
Read: PUDLELVIL LAVALELZIL. LUO, 2ILF pf IL, Hdd fds J
6103: Failure
Read: PUSLLAVIL LAVUALZI, 3920, 294/,.090, SI, O0OLVUJ
6104: Failure
Read: PUSLELVEL PLULZI.,IUI, 2IL/S UNU, SMI. 9Us J
6105: Failure
Read: PUSLELLIVIT PLULEZI, ULL, 2ILA ,VULL, MIL IIUJ
6106: Failure
Read: PUDSLELYVT PLULZI, VIL, 2ILLS  IUI, MIL III)
6107: Failure
Read: PUSLLIVIT PLULZI, UU, 29L0U,990, *U.ULIJ
6108: Failure
Read: PUSLELVEL PLULEZN.,.UUID, 2£ILV,IO/, SMU,UIO!)
6109: Failure
Read: PUSLLAVIL LAUALZI,. 224, 2949, 900, SI, 9011)
6110: Failure
Read: PUSLLEAVUIL LAVUAEZL HOU, £2919,.009, SI, 000)
6111: Failure
Read: PUSLLAVIT LAVACA. £20, 29744. 1L00, SIRIUS)
6112: Failure
Read: PUSLLAVIT LAVAELYU HIE, 2IVIA, LAS, WH SHY
6113: Failure
Read: FUSLELAVIL LAVULILO,OZI, "290U,.8991L, %9,000)
6114: Failure
Read: PUSLLIAVIT PAVLIAO., LID, 2IVI.,IVsA, SMI. UYI J
6115: Failure
Read: PUSLLIVIE PLVULILO,JOF, 27UU, 294, I. f/ / JJ
6116: Failure
Read: PUSALLIVIE PLVUICU,USU, 2O7/.,I91L0, 49.07%)
6117: Failure
Read: PUSLLIVIT PLVUICZA.,UIU, £2070,70U0, 49.9794)
6118: Failure
Read: PUSLLIVIT PLVICZAL., 9/2, LOF7I,0UIF, SI, 3991)
6119: Failure
Read: PUDSLELIAVUIT PLVICA. 42h, LOFI,.UIL, MI. III)
6120: Failure
Read: PUSLLEAVIT LAVALZY,., ULE, 2094. L240, SI, 9I1 4
6121: Failure
Read: PUSLELLVIT PLULIAD, UII, 2ZOIULZ,UIL, MI ILY J
6122: Failure
Read: PUSLELVIT PLULAS A IJ/U, 2009,93999, 9,700 J
6123: Failure
Read: PUSLLAVIT LAVUALY., L899, 2O0O/.ILf yy SMIII/ IJ
6124: Failure
Read: PUSLLAVIT LAVUALY. £UU, £00IN,.09I00, %9.,.4I9)
6125: Failure
Read: PUSLLAVIT LAVALI, 2UU, 2O09O.LIU, SI, 41414)
6126: Failure
Read: FPVUSLLAVIT PAULILV. OU, Z2O0U,7U00, %9, 24%)
6127: Failure
Read: FPUSLELEAVIL LAVULLO, ZL, Z2ZOfMA,VUII, WW, LEZ)
6128: Failure
Read: PUSLALIAVIE PLULAVD., 9UU, Zorg, UUYU, SH. W/s j
6129: Failure
Read: FUSLLEAVIL PAULIG, fIOI, ZOPIO,FUI, BH III)
6130: Failure
Read: PUSLLIAVIT PLULEU, SLU, £2O% 4. 9UL, HI INI]
6131: Failure
Read: PUDSDLELIAVIT PLYULEU, Of 9D, £2O'VU.AIZI4N, SI, OU!
6132: Failure
Read: PUSDLELVIT PLULEL,. UF, L£2ZOPW,. IID, UU. 29U4J
6133: Failure
Read: FPUSLELAVIT LPAVULEL. VIO, LOf/Zs,ILI, WVU, LI
6134: Failure
Read: PUDSLELAVIT PLVULECO,9UYU, Z2O/UL,ISF, MI, OU2 J
6135: Failure
Read: PUSLELEAVIL PAVLZIO, LIL, Z2ZOU0.9N ITU, NI, 794!
6136: Failure
Read: PUILA AU [PAUdsee, DA dy LOUG, 089, 8I,701!
6137: Failure
Read: PUDLL AVE! [AVAL L, GHD, L£0/VU,UIU, SIU J
6138: Failure
Read: PUDLALAUEL [AVUIALI, UN, 2OF LAVIN, MIU
6139: Failure
Read: PUSLALU [PsAUL LO, AHL, LOf/ hs Ff OH, NIO,HL£O)
6140: Failure
Read: PUSLELUI! [PAUlLisvy WLS, £0/£,7953, WO, £7 J
6141: Failure
Read: PUDALAVUEL PAVIA, c£f9, £O/GI, 490, SL, 7/014
6142: Failure
Read: PUSLELVIT LPLULIAZLZ. Ff 94, 2ZOPFI,UHL, MLL NNYUSI
6143: Failure
Read: PUDSLELVIT PLULIVA LIV, 2O6Z OZ, SWE, LLs J
6144: Failure
Read: PUSALIVIE PLVLVI, £70, Z2OrFU,.ALIO, 2,009)
6145: Failure
Read: PUSALLIVIE PLVULIAV, 90%, 42OUl -AJIL, SMELL ILI
6146: Failure
Read: PUSLLIVIE PLVULLO, VOU, Z20OUU, LIN, E.R I4]
6147: Failure
Read: PUSALIVIE PLVULAY, OHU, L2OUN,UIF, "WL. UU J
6148: Failure
Read: PUDSLLIAVIE PLVULLS ,9O90%7, LZOVI.AI/I, WL, OVI)
6149: Failure
Read: PUSALLIVIT PLVULAY. S971, £0UL,902Z2U, 49, Z2UV J
6150: Failure
Read: PUSALIVIE PLVUICZL., O/O, LZOUYU,LOL, 9, ULY J
6151: Failure
Read: PUSLLIVIE PLVI CEL, VLE, LOI9G, 2ID, MI. IN]J
6152: Failure
Read: PUSLLAVIT LAVUAECEL  HRU, 2£O0OIN0.201L, 89,19)
6153: Failure
Read: PUSLLAVUIL ~PAULE Lif 26 yy ZLOIDsUI!, ML, 97U1L J
6154: Failure
Read: PUSALLIAVIE PLVULCZO,/ 20, 2ZOI90,9% E297, %L,9O0LI4J
6155: Failure
Read: PUSLALIVIE PLULEY,O70, ZOYIL,.OFVI, %I,.2U/ J
6156: Failure
Read: PUSALIVIE PLVICZO, Les, LOYVY,IIY, SI, WIV J
6157: Failure
Read: PUSALLIVIT PLVLOVARLY, L209, 2490, 49.9702)
6158: Failure
Read: PUSLELIVIE PLVULOZ,. LAV, ZOHO ,.,.47Ll, 8H. NYUJ
6159: Failure
Read: PUSALIVIE PLVULOD,AVUILVU, ZOHO, 10, SH. / 214
6160: Failure
Read: PUSALIVIE PLVLOY, 220, 2OK/, 20, SI, YI J
6161: Failure
Read: PUSLLIVIT PLULOS , 29h, L2OKI, UNF, 4U,.,1074
6162: Failure
Read: PUSLELLVIT PLULIILUISI, L2LO8NI, 9429, / ,UUYUI
6163: Failure
Read: PUSLELLAVIT PLULIID. FLY, £O8N,.00/, SMF MILI
6164: Failure
Read: PUSLELLVEIT PLULIIG. FLY, £O8%,.0U0/, SMF MILI
6165: Failure
Read: PUSLELVIT PLULIDA Ff LI, £O8N.,.0U0/, SMF MILI
6166: Failure
Read: PUSLLIAVIT PLVULIG,IIN, L£OKN.,.UII, Wl LISI
6167: Failure
Read: PUSALLVIT PLULIO. UO, £089,429, %U,U1L04J
6168: Failure
Read: PUSALLIVIE PLVULIO,., 9£2U, LZOHKID,.4ID, SU. UID]
6169: Failure
Read: PUSLLIVIE PLVLOO, O47, ZOHI, ILL, UL ULZJ
6170: Failure
Read: PUSLLIVIE PLVULOS ,OYUY, ZOHO,UIYU, SU, UU J
6171: Failure
Read: PUSLLIVIE PLYULIO,.UUU, ZOHO, fy, O,.,1Z2ZUJ
6172: Failure
Read: PUSLELIAVIT PLVLOO, 2ZUL, 209,100, 0,10 J
6173: Failure
Read: PUSALLAVIT LPAVLIO,. 2UL, £209%9,.,100, 90.102)
6174: Failure
Read: PUSLELIVIT PLVULOS .f LS, ZOHO, 001L, Wl. BIJ
6175: Failure
Read: PUSLELLVIT PLULOIVA LILO, a£oso,9g97U, %U,999)
6176: Failure
Read: FPUSDLELAVIL PAULIN, 2ZZ9, ZLOW/ -Yl ly, MI, LU)
6177: Failure
Read: PUSLLIVIT PLULOD. Uf, £067 .9UF7, 4H. 9/04
6178: Failure
Read: PUSLLIVIE PLVULOD,. UY, £07 .,.9UF7, WH. 34/04
6179: Failure
Read: PUSLLIVIT PLVLOD,. Uf, £207,907, 4H. 397/04
6180: Failure
Read: PUSALIAVIE PLVULOD,. YU, £067,907, 4H. 397/04
6181: Failure
Read: PUSALIAVIE PLVLOD,. VU, £067,907, 4H. 397704
6182: Failure
Read: PUSALIAVIE PLVULOD,. YU, £067,907, 44H. 97/04
6183: Failure
Read: PUSALIVIE PLVULOD,. VU, £067,907, 4H. 397/04
6184: Failure
Read: PUSALIAVIE PLVULOD,. VU, £067,907, 44H. 597/04
6185: Failure
Read: PYyDLeELV! ~PLYloo., SUF, 2087 ,.80797, 4H. af O]
6186: Failure
Read: PYyDLeELV! ~PLYloo., SUF, 2087 ,.80797, 4H. af O]
6187: Failure
Read: PYyDLeELV! ~PLYloo., SUF, 2087 ,.80797, 4H. af O]
6188: Failure
Read: PYyDLeELV! ~PLYloo., SUF, 2087 ,.80797, 4H. af O]
6189: Failure
Read: PYyDLeELV! ~PLYloo., SUF, 2087 ,.80797, 4H. af O]
6190: Failure
Read: PUSALIVIE PLVLOD,. ZU, £067,907, 4H. 397/04
6191: Failure
Read: PUSALIVIE PLVULOD,. VU, £067,907, 44H. 59/04
6192: Failure
Read: PUSDLELAVUIL PAVULID. IU, £20%/ .8UDI, WH, 7 OJ
6193: Failure
Read: PUSLELAVUIL PAVULID. IU, £20%/ .9UF, WH, 7/ OJ
6194: Failure
Read: PUSLELAVIL PAVLOV. IU, £20%/ .8UDI, WH, FIO]
6195: Failure
Read: PUDLELAVUIL PAVULID. IU, £20%/ .9UF, WH, 7/1 OJ
6196: Failure
Read: PUSLELAVUIL PAVULID. IU, £20%/ .9UF, WH, 7/ OJ
6197: Failure
Read: PUDLELAVIL PAVULIOD. IU, £20%/ .9UDI, WH, 7 OJ
6198: Failure
Read: PUDLLEAVIL PAVULID. IU, £2097 .9UF, WH, 7/1 OJ
6199: Failure
Read: PUSDLELAVIL PAVULID. IU, £20%/ .8UDF, WH, 7/1 OJ
6200: Failure
Read: PUSDLELAVIL PAVULIOD. IU, £20%/ .8UF, WH, 7 OJ
6201: Failure
Read: PUSLELAVIL PAVLOV. IU, £20%/ .8UDI, WH, FIO]
6202: Failure
Read: PUSLELAVUIL PAVLOV. IU, £20%/ .9UF, WH, 7 OJ
6203: Failure
Read: PUSLELAVUIL PAVULIOD. IU, £20%/ .8UF, WH, 7D)
6204: Failure
Read: PUSLELAVIL PAVLOV. IU, £20%/ .8UDI, WH, FIO]
6205: Failure
Read: PUDLEAVIL PAVULIOD. IU, £20%/ .8UDI, WH, 7 OJ
6206: Failure
Read: PypaLeLv! ~PLYvloo., SUF, 2087 ,.8079, WH. 2d]
6207: Failure
Read: PUSDLELAVIL PAVULIOD. IU, £20%/ .8UF, WH, 7 OJ
6208: Failure
Read: PUDLELAVIL PAVULID. IU, £20%/ .8UD, WH, 7/1 OJ
6209: Failure
Read: PUSLELAVUIL PAVULID. IU, £20%/ .9UF, WH, 7/ OJ
6210: Failure
Read: PUSLELAVUIL PAVULID. IU, £20%/ .8UDI, WH, FIO]
6211: Failure`

**Comment by RRadziejewski** [comment]
Where is it hard coded i've look for 1920 token and havent seen

**Comment by raffertyj** [comment]
what y'all are seeing is the ocr failing to read the position. for example, it's seeing "PUSLLAVIT" or "PUSLELVIT" instead of "Position". if you windowed your game window and wiggled it around slowly in the top right corner of your main monitor, you could probably get it to eventually read, i did that. but ideally we're playing in fullscreen in any resolution.

i think the program needs to grab the games window for the location, or at least this information then it can go from the corner to try and get the position.

**Comment by Typ33** [comment]
Changed to windowed Mode and 1920 x 1080

Total count=0
Min=0.00 Really=0
Lower quartile=0.00
Median=0.00, ile(0.5)=0.00
Upper quartile=0.00
Max=0.00 Really=0
Range=1
Mean= 0.00
SD= 0.00
Read:
576: Failure
Bottom=0, top=288, base=0, x=0
