### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by convict-vx** [CptWesley/NewWorldMinimap#4]
An in map legenda that shows wich icon stands for wich resource / plant. ive seen the ore icon in red and blue allready so im guessing iron and maybe silver.

Maybe slower ocr speed (or option for it) (i mean the scanning speed with this) as for now my map jumpas a bit around (showing me a different position than where i am, works good just annoying) as the map jumps way too often. making me blind when it thinks im at the ocean.

For the rest it works nicely for me, just the map jumpingm but im sure it has to do with my settings or the nvidia filter.

**Comment by CptWesley** [comment]
Closing because all of the mentioned features are either not applicable or already implemented in the overwolf version.
