### ISSUE TITLE
Change how map is rendered

### ISSUE THREAD

**Issue by AlessioDP** [CptWesley/NewWorldMinimap#45]
The usage of canvas drawing should be dropped. The __only__ game map should be inside a canvas and all other elements, like markers, placed above it.

This will allows us to improve markers, and any other thing on the map, better with custom styling and mouse events.

**Comment by CptWesley** [comment]
Tests have shown that we wouldn't be able to achieve similar performance when rendering everything in the DOM, so I'm closing this issue for now.
