### ISSUE TITLE
App causing CPU temperatures to skyrocket while running.

### ISSUE THREAD

**Issue by toxie** [CptWesley/NewWorldMinimap#8]
Just a concern but for whatever reason this application causes my CPU temperatures to run hotter than any other application I've ever ran on this machine (65-67c)
No bench marking app nor Video Encoder can even get my CPU this high but your application has no trouble doing just that within just a few seconds after launching and its cpu usage is only about 5%.
At best these other applications can get the cpu to 65c and no higher only after about about 15-20minutes of runtime.

**Comment by CptWesley** [comment]
Performance drastically increased in overwolf version. Therefor closing.
